### ISSUE TITLE
RAxML quits with error

### ISSUE THREAD

**Issue by SheaML** [FePhyFoFum/quartetsampling#2] opened 2017-06-12 19:46 UTC
Hi,

I'm getting a "File not found" error for  ".../temp/RAxML_results" files (which are indeed not being produced). By re-running the "RAxML was called as follows:"  line for one of these, I can see that I get the following error from RAxML:

"raxmlHPC-AVX: evaluateGenericSpecial.c:3514: evaluateIterative: Assertion `partitionLikelihood < 0.0' failed.
Aborted"

The chunk of data being analyzed here has 455 alignment patterns and 12.65% undetermined characters. 

I've seen this error mentioned a few times on the RAxML users group, and typically it does seem to be the result of a bug rather than something related to the input file. I will make a post on the raxml users group, but I thought I would mention it here as well as I haven't seen the error in my own RAxML use. I've tried pointing quartetsampling to a few different RAxML executables (PTHREADS and serial, AVX/SSE3) and get the error regardless.

**Comment by jbpease** [comment] 2017-06-13 02:56
Hi SheaML,

Try turning on `-v/--verbose`.  If you see a message that says "PARTITIONS WARNING OR MISSING DATA FROM RAXML"  then this means you don't have sufficient data in one or more of your partitions to do a partition-based analysis.  This is a side-effect of a quartet-based analysis in data that is both sparse and partitioned, where sometimes RAxML will try (and fail) to evaluate an empty quartet where all the randomly selected sequences happen to contain gaps for one or more partitions. 

In QS, you can override the RAxML errors with the `--ignore errors` flag.  
You can also check the RAxML log files in the temporary directory and they may also point out what's happening.

let me know if this resolves the issue.

**Comment by SheaML** [comment] 2017-06-13 18:30
Hi James,

Using verbose, I don't see any "PARTITIONS WARNING OR MISSING DATA FROM RAXML"  messages. Also, --ignore-errors doesn't avoid the issue. Someone from the RAxML team got back to me, so I'll let you know if there is any progress. 

Thanks,
Shea

**Comment by amkozlov** [comment] 2017-06-14 12:57
Hi James,

there seems to be a RAxML bug which I can reproduce, although it occurs under **very** specific conditions.  Before I invest a lot of time trying to hunt it down, could you please explain why do you want to run a complete tree search on a 4-taxon alignment? Wouldn't it be sufficient to evaluate logLH on all 3 possible topologies (and mb re-optimize the branches)?

Although please consider moving to RAxML-NG, since it's very time-consuming to debug and maintain old RAxML code.

Best,
Alexey

**Comment by jbpease** [comment] 2017-07-11 11:31
Hi Alexey,

We will take a look at both of these issues and take a look at RAxML-NG too.  Thanks for the tip.  We went with the standard, since that's what most folks use and have installed on clusters, etc.

James

**Closed** 2018-03-17 03:31 UTC
Labels: enhancement
